name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v4.0.0
      - run: poetry install --extras all
      - run: poetry run pytest -v

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v4.0.0
      - run: poetry install --extras all
      - run: poetry run flake8
      - run: poetry run mypy --ignore-missing-imports .
      - run: poetry run isort --check --diff .
      - run: poetry run black --check --diff .
